; Lab #1: GPIO basics — STM32F407VGT6 (Discovery board)
; Two firmware variants selected via build environments:
;   pio run -e blink          -> src/main_blink.c     (single LED on PA0)
;   pio run -e running_light  -> src/main_running.c   (running light PA0-PA3)

[platformio]
default_envs = blink

[env:blink]
platform = ststm32
board = disco_f407vg
framework = stm32cube
build_src_filter = -<*> +<main_blink.c>

[env:running_light]
platform = ststm32
board = disco_f407vg
framework = stm32cube
build_src_filter = -<*> +<main_running.c>

[env:running_reverse]
platform = ststm32
board = disco_f407vg
framework = stm32cube
build_src_filter = -<*> +<main_reverse.c>

[env:running_bounce]
platform = ststm32
board = disco_f407vg
framework = stm32cube
build_src_filter = -<*> +<main_bounce.c>

[env:running_fast]
platform = ststm32
board = disco_f407vg
framework = stm32cube
build_src_filter = -<*> +<main_fast.c>
